
# application.yml VS application.properties??
#???????? ???? ???? ?? ??? ????, ??????? ??? ? ???? ???? ??.
#
#spring boot? ?????? ???? ?? ??? ????? ?? ??? ???(?? API Key ??) ?? ??? ????? ??? ?? ???? ??? ???.
#?? ??? ??????? ??? ????.
#
#?? ?????? ????? ??? application.properties? ????? ????.
#?? application.yml? ???? ???? Refactor->Rename?? ???? yml? ???? ??.
#application.properties -> key-value ???? ?? ??
#application.yml -> ??? ???? ?? ??. prefix ???? ??

#Configuration? ??? ?, ??? ??/?? ???? ???? ??? ?? ex) ????, ? ????, ???? ??...

spring:
  datasource:
    # DB Connection ?? ??
    url: jdbc:mariadb://172.16.131.11:3306/clinic_1234
    username: tes_admin
    password: 'tjdrhd@roqkf&'
    driver-class-name: org.mariadb.jdbc.Driver
  datasource1:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 'root'
    driver-class-name: org.mariadb.jdbc.Driver
